In [37]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.model_selection import train_test_split
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, IterativeImputer
from sklearn.metrics import confusion_matrix, classification_report 
from sklearn.utils.class_weight import compute_class_weight

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [38]:
df = pd.read_pickle("cleanDataDraft1.pkl")

In [39]:
imp = IterativeImputer(estimator=ExtraTreesRegressor(), missing_values=np.nan)
x = df.drop('hiedinch', axis=1)
y = df.hiedinch
x = imp.fit_transform(x)



c:\users\pkrat\documents\competitions\data_mining_comp\venv\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\pkrat\documents\competitions\data_mining_comp\venv\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\pkrat\documents\competitions\data_mining_comp\venv\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\pkrat\documents\competitions\data_mining_comp\venv\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 

In [41]:
x

array([[1., 4., 1., ..., 0., 0., 0.],
       [2., 1., 1., ..., 0., 0., 0.],
       [1., 1., 2., ..., 0., 0., 0.],
       ...,
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 3., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.]])

In [47]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4)

In [98]:
clf = RandomForestClassifier(class_weight={0:1, 1:10})

In [99]:
clf.fit(X_train, y_train)

c:\users\pkrat\documents\competitions\data_mining_comp\venv\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight={0: 1, 1: 10},
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=10, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [100]:
clf.score(X_test, y_test)

0.908

In [101]:
y_true = y

y_pred = clf.predict(x)

In [102]:
conf_matrix = confusion_matrix(y_true, y_pred)

In [103]:
conf_matrix

array([[8774,   85],
       [ 342,  799]], dtype=int64)

In [104]:
(df[df.child == 0].shape[0]) / (df[df.child == 1].shape[0])

3.310481586402266

In [105]:
weigh_1 = df[df.hiedinch == 0].shape[0] / df[df.hiedinch == 1].shape[0] 

In [106]:
np.unique(df.child)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [109]:
weights = np.array([[1300, -500], [0, 0]])
weights

array([[1300, -500],
       [   0,    0]])

In [110]:
np.sum(np.multiply(conf_matrix, weights))

11363700

In [111]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98      8859
           1       0.90      0.70      0.79      1141

    accuracy                           0.96     10000
   macro avg       0.93      0.85      0.88     10000
weighted avg       0.96      0.96      0.95     10000



array([44., 55.])